apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kuard-gw
  namespace: kuard-test
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "sanjay-mesh.apps.killer.lab.upshift.rdu2.redhat.com"
