apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kuard-vs
  namespace: kuard-test
spec:
  hosts:
    - "xxxxxxxxxx"
  gateways:
    - kuard-gw
  http:
    - match:
        - uri:
            prefix: "/green"
      route:
        - destination:
            host: kuard
            subset: kuard-green
    - match:
        - uri:
            prefix: "/blue"
      route:
        - destination:
            host: kuard
            subset: kuard-blue
            
